### ISSUE TITLE
哪些信息是要在数据库中预先导入的？哪些信息是需要在部署后添加？

### ISSUE THREAD

**Issue by Ulden** [SystemDesignGroup/Hospital#2]
举例说明：
- city需要预先导入
- users需要部署后添加
- grade需要预先导入
- ......

**Comment by shtb** [comment]
管理员部分已完成，可以自动添加city,grade,major,calendar(I 'm not sure what this means),可以通过网页添加hospital,department,doctor.

**Comment by Ulden** [comment]
我说的预先导入的意思就是指静态值。你说的自动添加是怎么意思，没太懂。。。。。

**Comment by shtb** [comment]
因为医院，科室，医生依赖于城市，等级之类的，所以在添加医院时会先检查数据库中是否有对应城市，没有的话会先添加城市再添加医院。其他的同理。所以城市之类的应该不用特意添加。

**Comment by Ulden** [comment]
我觉得应该把静态的数据都提前导入数据库。如果是添加医院时候在添加的话可能会出现非法地址。比如城市写“帝都”这种。

**Comment by shtb** [comment]
可以，不过需要统一一下数据吧，用admin/editHospital.html里的数据怎么样？

**Comment by Ulden** [comment]
城市就用那个吧，我整理了之后直接导了。其它的静态数据也导了吧，比如医院的等级有“三甲”什么的、医生的等级有“主治医师”什么的，医院的专业类别有“男科医院”这种。静态数据应该就这几个了吧？还有别的么？

**Comment by shtb** [comment]
应该没了吧，话说医院的major和医生的major应该是什么？是一样的么？还有calendar是干嘛的？

**Comment by Ulden** [comment]
calendar是医生的排班。字段具体的意思看一下文档就知道了。医生和医院的major应该是一样的啊，男科大夫，男科医院。

**Comment by Ulden** [comment]
现在城市还有医院和医生的grade已经添加进去了。major不知道都有啥，所以没加进去。
